--- #YAML:1.0
name:               Net-Chaton-API
version:            0.01
abstract:           WebAPI for Chaton.
author:
    - Pocket <poketo7878@yahoo.co.jp>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
